#spring.profiles.active = local
#spring.main.web-environment = true
server:
  port: 8081
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  http:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/giftzzel?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  mail:
      host: smtp.gmail.com
      port: 587
      username: garimanarola@gmail.com
      password: j76N4sxE7169uXv
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
#logging
#logging:
#    level:
#        ROOT: INFO
#        com.party.giftzzel: INFO
#logging:
#  config : "config/log4j2.xml"

#security:
#  authentication:
jwt:
  secret: "my-secret-token-to-change-in-production"
  # Token is valid 24 hours
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 2592000

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 1800

giftzzel:
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: giftzzel@localhost
    base-url: http://127.0.0.1:8080
  no-of-files: 5
# Multipart Configuration
multipart:
  location: /Uploads
  maxFileSize: 100Mb
  maxRequestSize: 100Mb
  fileSizeThreshold: 10Mb
logging:
  level:
    org:
      hibernate:
        SQL: debug